# Generated by Django 4.1.7 on 2023-02-25 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
