# Generated by Django 4.1.7 on 2023-02-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobots', '0002_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbMenus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TbRules',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('father_id', models.IntegerField()),
                ('rule_name', models.CharField(max_length=100)),
                ('is_menu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TbUsers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
